### ISSUE TITLE
First run impression - Documentation

### ISSUE THREAD

**Issue by yn-alex** [SimplyStaking/panic_cosmos#1]
Hi,

I just installed PANIC and tested some of it's alerts. I find it useful with great potential especially after achieving a more granular configuration - thresholds, specific alerts (on/off), maybe customizing alerts and so on.

Things that I had to do outside the documentation in order to make it work:

1.  Make sure you are running the correct python version. If you have more binaries, run the correct one. Example:
` pipenv run python3.6 run_setup.py instead of pipenv run python run_setup.py`

2. I had to manually install the following libraries else the setup wouldn't work:
```
pip install twilio
pip install python-telegram-bot  ## Not the library named simply "telegram" !
pip install redis
pip install python-dateutil
```

**Comment by migueldingli1997** [comment]
Hi @yn-alex,

We appreciate that you installed and tested PANIC. The process for achieving more granular settings could be better and it's in our ToDo lists :)

Regarding your messages:
1. Good point, this should be clear in the documentation.
2. The `pipenv update` step in the documentation should do this automatically. It uses the included `Pipfile`, which includes the libraries that you listed, to install all dependencies.
